[package]
name = "hub"
version = "3.0.16"
edition = "2021"
authors = ["larry <gm@larry.engineer>", "PFC <pfc-validator@protonmail.com>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/st4k3h0us3/steak-contracts"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.5.4", features = ["staking"] }
cosmwasm-schema = { version = "1.5.4" }
cw2 = "1.0.0"
cw20 = "1.0.1"
cw20-base = { version = "1.0.0", features = ["library"] }
cw-storage-plus = "0.13"

steak = { path = "../../packages/steak" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
pfc-fee-split = "0.2.3"
#pfc-dust-collector = {path = "../../packages/pfc-dust-collector"}
funds-distributor-api = { git = "https://github.com/terra-money/enterprise-contracts.git", branch = "main" }
#[dev-dependencies]
#serde = { version = "1.0.103", default-features = false, features = ["derive"] }
